### ISSUE TITLE
你好，在B站看了你的视频，遇到问题，想问下怎么解决？

### ISSUE THREAD

**Issue by io-o** [Gourouting/singo#1]
![image](https://user-images.githubusercontent.com/22197685/61185508-f5bdce00-a68c-11e9-80ae-c7b4bd174430.png)
是需要翻墙下载 go-redis么？ 
我翻墙执行： go get  github.com/go-redis/redis没用。

**Comment by jiangliu2u** [comment]
用gopm

**Comment by bydmm** [comment]
这个是本地没有启动redis
