### ISSUE TITLE
go get gihtub.com/bydmm/singo报错

### ISSUE THREAD

**Issue by JohnieXu** [Gourouting/singo#11]
错误如下
```
package singo/conf: unrecognized import path "singo/conf" (import path does not begin with hostname)
```
错误应该是man.go中导入模块未指定hostname

**Comment by L-HeliantHuS** [comment]
建议你使用git clone https://gihtub.com/bydmm/singo.git 来进行代码获取

框架使用了go mod， 你要在环境变量开启GO111MODULE = on 顺便配置GOPROXY=https://goproxy.io

就直接可以go run main.go进行启动了。

**Comment by Xiangrui2019** [comment]
这个不是包，这个是一个项目模板，请注意。

**Comment by Xiangrui2019** [comment]
此issue将保留一天，请将您的问题在明天19点之前发给我
