### ISSUE TITLE
返回403 

### ISSUE THREAD

**Issue by lmx01** [Gourouting/singo#22]
请问下post请求的时候，403会是什么原因尼？谢谢
![image](https://user-images.githubusercontent.com/16526407/70720683-35b5d980-1d2f-11ea-9a78-a1bff664b4da.png)

**Comment by iscraft** [comment]
@lmx01 请问一下,这个403的错误最终是怎么解决掉的?谢谢!

**Comment by lmx01** [comment]
> @lmx01 请问一下,这个403的错误最终是怎么解决掉的?谢谢!
![image](https://user-images.githubusercontent.com/16526407/71652855-ba5eab00-2d63-11ea-800e-3e4843bc9c20.png)
- 如上，我是电脑里面有两个postman,用第一个就没有403问题；
- 后面教学会讲，403是跨域问题，解决方案是需要在代码里面配置下

**Comment by williammyuan** [comment]
参考这个可以解决：[返回403解决方案](https://github.com/Gourouting/singo/issues/25)
