### ISSUE TITLE
怎么配置多个数据库实例/多个数据库访问呢

### ISSUE THREAD

**Issue by lumening** [Gourouting/singo#34]
例如：两个数据库地址127.0.0.1:3006|127.0.0.1:3007，这两个数据库地址分别都有两个database: user、customer；config、other等四个database。我现在需要在同一个项目访问四个数据库里面的表。我连接mysql的代码应该怎么写比较好呢，项目里面并没有相关的说明，只有简单的单个数据库连接并不十分实用。

**Comment by bydmm** [comment]
这个要自行增加一个dao层，把数据库连接和model分开。不过现在流行微服务思维，如果有四个数据库建议四个不同的项目。singo其实也能支持这种架构，无非是nginx转发作为gateway，转发不同的路由到不同的singo项目，每个项目一个数据库
