### ISSUE TITLE
GIN_MODE在.env中配置时，无法正常识别, 必须在系统环境变量设置

### ISSUE THREAD

**Issue by Xiangrui2019** [Gourouting/singo#9]
这个问题非常玄学

**Comment by L-HeliantHuS** [comment]
嘻嘻嘻...我来凑个热闹。

**Comment by Xiangrui2019** [comment]
> 嘻嘻嘻...我来凑个热闹。

别闹事，别凑热闹，人家不就是开个PR。

**Comment by jiangbo202** [comment]
我也遇到这个问题，不知道是不是配置有啥问题，请指点

**Comment by L-HeliantHuS** [comment]
> > 嘻嘻嘻...我来凑个热闹。
> 
> 别闹事，别凑热闹，人家不就是开个PR。



> 我也遇到这个问题，不知道是不是配置有啥问题，请指点

说了玄学嘛~ windows会遇到这个问题~

**Comment by codetown** [comment]
不是玄学，根本原因是在go.mod需要引入github.com/karrick/godirwalk v1.10.12 // indirect这个包
@Xiangrui2019 @jiangbo202

**Comment by Xiangrui2019** [comment]
> 不是玄学，根本原因是在go.mod需要引入github.com/karrick/godirwalk v1.10.12 // indirect这个包
> @Xiangrui2019 @jiangbo202

默认的引用为啥不见了？？？？？

**Comment by codetown** [comment]
应该是这个包github.com/joho/godotenv v1.3.0 ，上次发错了

**Comment by L-HeliantHuS** [comment]
> 应该是这个包github.com/joho/godotenv v1.3.0 ，上次发错了

怎么会, 已经引用了啊。 不然MYSQL的连接也获取不到了。

**Comment by Xiangrui2019** [comment]
> 应该是这个包github.com/joho/godotenv v1.3.0 ，上次发错了

Why？

**Comment by bydmm** [comment]
解了。
